name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Greet First-Time Contributors
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: |
            👋 **Welcome to the Logistics Portfolio project!**

            Thank you for opening your first issue. We appreciate your contribution and are here to help you succeed.
            Please provide as much detail as possible so we can assist you quickly.

            _Happy coding!_
          pr-message: |
            🎉 **Thank you for your first pull request!**

            We are excited to see your contribution to the Logistics Portfolio project.
            Our team will review your PR as soon as possible. If you have any questions, feel free to ask.

            _Welcome to the community!_
    # Documentation:
    # - This workflow greets new contributors on their first issue or PR.
    # - Customize messages above to reflect your project's tone and guidelines.
