# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler

name: PR Labeler (Professional)
description: >
  Automatically labels pull requests based on changed file paths using .github/labeler.yml.
  Ensures all PRs are triaged for review and release automation.

on:
  pull_request_target:
    types: [opened, synchronize, reopened, labeled, unlabeled]

jobs:
  label:
    name: Apply Labels
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Run Labeler
        uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Check for labeler errors
        if: failure()
        run: |
          echo "Labeler failed. Please check .github/labeler.yml for syntax or pattern errors."
          exit 1
    # Documentation:
    # - See .github/labeler.yml for rules.
    # - Update labeler.yml when adding new features or directories.
